all:
	emcc ../पर्वयन्त्रम्/पर्वयन्त्रम्.c -s WASM=1 -o पर्वयन्त्रम्.js -s NO_EXIT_RUNTIME=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['ccall']" -s EXPORTED_FUNCTIONS="['_उपक्रमः', '_नवपर्व', '_नवप्रयोगः', '_मार्जनम्']"
