all:
	emcc ../पर्वयन्त्रम्/पर्वयन्त्रम्.c -s WASM=1 -o पर्वयन्त्रम्.js -s NO_EXIT_RUNTIME=1 -s "EXTRA_EXPORTED_RUNTIME_METHODS=['cwrap']" -s EXPORTED_FUNCTIONS="['_नवपर्व', '_नवप्रयोगः', '_मूलपर्व', '_वामकपर्व', '_दक्षिणकपर्व', '_मार्जनम्']"
